services:
  frontend:
    image: ghcr.io/brwwang/portfolio-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://api-server:4000
  backend:
    build:
      context: ./apps/api-server
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:8.0
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=[PASSWORD]

volumes:
  mongo_data: