FROM python:3.12-slim as build

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

FROM build AS development

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4000", "--reload"]

FROM build AS production

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4000"]