FROM node:24-alpine AS build
WORKDIR /app

COPY ./package-lock.json ./
COPY ./apps/astro-server/package.json ./
RUN npm ci

COPY ./apps/astro-server .
RUN npm run build


FROM node:24-alpine AS runtime
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=4321

EXPOSE ${PORT}

COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./
RUN npm ci --omit=dev

EXPOSE 4321

CMD ["node", "./dist/server/entry.mjs"]
