FROM node:24-alpine AS base
WORKDIR /app

COPY ./package-lock.json ./package.json ./

RUN npm ci

FROM base AS development

COPY . .

ENV NODE_ENV=development

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

FROM base AS build

COPY . .

RUN npm run build


FROM node:24-alpine AS production
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOST=0.0.0.0

EXPOSE ${PORT}

COPY --from=build /app/dist ./dist
COPY --from=build /app/package-lock.json /app/package.json ./
RUN npm ci --omit=dev 

CMD ["node", "./dist/server/entry.mjs"]
