name: CI_CD

on:
    push:
        branches: main
        paths:
            - "apps/**"
            - ".github/workflows/ci_cd.yml"

permissions:
    contents: read
    packages: write

jobs:
    changes:
        runs-on: ubuntu-latest
        
        outputs:
            frontend: ${{steps.filter.outputs.frontend}}
            backend: ${{steps.filter.outputs.backend}}

        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v4
              id: filter
              with:
                  filters: |
                      frontend: "apps/astro-server/**"
                      backend: "apps/github-service/**"
                      compose: "docker-compose.yml"

    frontend-lint:
        needs: changes
        if: ${{needs.changes.outputs.frontend == 'true'}}
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: apps/astro-server
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "24.x"
            - name: Install dependencies
              run: npm ci
            - name: Check formatting
              run: npx prettier --check "**/*.{js,ts,astro,css}"

    frontend-build:
        needs: frontend-lint
        uses: ./.github/workflows/frontend_build.yml
        secrets: inherit

    backend-build:
        needs: changes
        if: ${{needs.changes.outputs.backend == 'true'}}
        uses: ./.github/workflows/backend_build.yml
        secrets: inherit

    deploy:
        needs: [frontend-build, backend-build]
        if: |
            always() &&
            (
            needs.frontend-build.result == 'success' ||
            needs.backend-build.result == 'success'
            ) && (
            needs.frontend-build.result != 'failure' &&
            needs.backend-build.result != 'failure'
            )
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        
