name: CI_CD

on:
    push:
        branches: main
        paths:
            - "apps/**"
            - ".github/workflows/ci_cd.yml"

permissions:
    contents: read
    packages: write

jobs:
    changes:
        runs-on: ubuntu-latest

        outputs:
            frontend: ${{steps.filter.outputs.frontend}}
            backend: ${{steps.filter.outputs.backend}}

        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v4
              id: filter
              with:
                filters: |
                    frontend: "apps/astro-server/**"
                    backend: "apps/github-service/**"
    
    frontend-lint:
        needs: changes
        if: ${{needs.changes.outputs.frontend == 'true'}}
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: apps/astro-server
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "24.x"
            - name: Install dependencies
              run: npm ci
            - name: Check formatting
              run: npx prettier --check "**/*.{js,ts,astro,css}"
    
    frontend-build:
        runs-on: ubuntu-latest
        needs: frontend-lint
        defaults:
            run:
                working-directory: apps/astro-server
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "24.x"
                  cache: "npm"
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_PASSWORD }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4
            - name: Build and Push to GitHub Container Registry
              uses: docker/build-push-action@v6
              with:
                  context: ./apps/astro-server
                  push: true
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  tags: |
                      ghcr.io/${{ secrets.GHCR_TAG }}/frontend:latest
                      ghcr.io/${{ secrets.GHCR_TAG }}/frontend:${{ github.sha }}

    backend-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: apps/github-service
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_PASSWORD }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4
            - name: Build and push to GHCR
              uses: docker/build-push-action@v6
              with:
                  context: ./apps/github-service
                  file: ./apps/github-service/Dockerfile
                  push: true
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  tags: |
                      ghcr.io/${{ secrets.GHCR_TAG }}/backend:latest
                      ghcr.io/${{ secrets.GHCR_TAG }}/backend:${{ github.sha }}


    deploy:
        runs-on: ubuntu-latest
        needs: [frontend-build, backend-build]
        if: |
            always() &&
            (
            needs.frontend-build.result == 'success' ||
            needs.backend-build.result == 'success'
            ) && (
            needs.frontend-build.result != 'failure' &&
            needs.backend-build.result != 'failure'
            )
        steps:
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_PASSWORD }}
            - name: Login to VPS
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                    echo "test" >> test.txt